spring.application.name=smartattendance

spring.datasource.url=jdbc:mysql://root:dzIJneGuPOXwzDkNDAREKqeBgXnnseHo@shinkansen.proxy.rlwy.net:48525/railway
spring.datasource.username=root
spring.datasource.password=dzIJneGuPOXwzDkNDAREKqeBgXnnseHo

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
